In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [2]:

df = pd.read_csv('D:\\AILAB\\Project\\ADANIPORTS.csv')
df

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2007-11-27,MUNDRAPORT,EQ,440.00,770.00,1050.00,770.00,959.0,962.90,984.72,27294366,2.687719e+15,NaN,9859619,0.3612
1,2007-11-28,MUNDRAPORT,EQ,962.90,984.00,990.00,874.00,885.0,893.90,941.38,4581338,4.312765e+14,NaN,1453278,0.3172
2,2007-11-29,MUNDRAPORT,EQ,893.90,909.00,914.75,841.00,887.0,884.20,888.09,5124121,4.550658e+14,NaN,1069678,0.2088
3,2007-11-30,MUNDRAPORT,EQ,884.20,890.00,958.00,890.00,929.0,921.55,929.17,4609762,4.283257e+14,NaN,1260913,0.2735
4,2007-12-03,MUNDRAPORT,EQ,921.55,939.75,995.00,922.00,980.0,969.30,965.65,2977470,2.875200e+14,NaN,816123,0.2741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3317,2021-04-26,ADANIPORTS,EQ,725.35,733.00,739.65,728.90,729.2,730.75,733.25,9390549,6.885658e+14,116457.0,838079,0.0892
3318,2021-04-27,ADANIPORTS,EQ,730.75,735.00,757.50,727.35,748.6,749.15,747.67,20573107,1.538191e+15,236896.0,1779639,0.0865
3319,2021-04-28,ADANIPORTS,EQ,749.15,755.00,760.00,741.10,743.4,746.25,751.02,11156977,8.379106e+14,130847.0,1342353,0.1203
3320,2021-04-29,ADANIPORTS,EQ,746.25,753.20,765.85,743.40,746.4,746.75,753.06,13851910,1.043139e+15,153293.0,1304895,0.0942
3321,2021-04-30,ADANIPORTS,EQ,746.75,739.00,759.45,724.50,726.4,730.05,743.35,12600934,9.366911e+14,132141.0,3514692,0.2789

In [44]:
x = df
x['year'] = pd.DatetimeIndex(x['Date']).year
x['month'] = pd.DatetimeIndex(x['Date']).month
x['day'] = pd.DatetimeIndex(x['Date']).day
x = df.drop(['%Deliverble','Date','Symbol','Series'],axis = 1)
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3322 entries, 0 to 3321
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Prev Close          3322 non-null   float64
 1   Open                3322 non-null   float64
 2   High                3322 non-null   float64
 3   Low                 3322 non-null   float64
 4   Last                3322 non-null   float64
 5   Close               3322 non-null   float64
 6   VWAP                3322 non-null   float64
 7   Volume              3322 non-null   int64
 8   Turnover            3322 non-null   float64
 9   Trades              2456 non-null   float64
 10  Deliverable Volume  3322 non-null   int64
 11  year                3322 non-null   int64
 12  month               3322 non-null   int64
 13  day                 3322 non-null   int64
dtypes: float64(9), int64(5)
memory usage: 363.5 KB

In [45]:
y=df['%Deliverble']
Y=df['%Deliverble']
y

0       0.3612
1       0.3172
2       0.2088
3       0.2735
4       0.2741
         ...
3317    0.0892
3318    0.0865
3319    0.1203
3320    0.0942
3321    0.2789
Name: %Deliverble, Length: 3322, dtype: float64

In [46]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =0.30)

In [47]:
print("xtrain shape : ", xtrain.shape)
print("xtest shape  : ", xtest.shape)
print("ytrain shape : ", ytrain.shape)
print("ytest shape  : ", ytest.shape)

xtrain shape :  (2325, 14)
xtest shape  :  (997, 14)
ytrain shape :  (2325,)
ytest shape  :  (997,)

In [48]:
x['Trades'] = x['Trades'].fillna(method = 'bfill')
x['Trades']

0        19171.0
1        19171.0
2        19171.0
3        19171.0
4        19171.0
          ...
3317    116457.0
3318    236896.0
3319    130847.0
3320    153293.0
3321    132141.0
Name: Trades, Length: 3322, dtype: float64

In [49]:
x

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,year,month,day
0,440.00,770.00,1050.00,770.00,959.0,962.90,984.72,27294366,2.687719e+15,19171.0,9859619,2007,11,27
1,962.90,984.00,990.00,874.00,885.0,893.90,941.38,4581338,4.312765e+14,19171.0,1453278,2007,11,28
2,893.90,909.00,914.75,841.00,887.0,884.20,888.09,5124121,4.550658e+14,19171.0,1069678,2007,11,29
3,884.20,890.00,958.00,890.00,929.0,921.55,929.17,4609762,4.283257e+14,19171.0,1260913,2007,11,30
4,921.55,939.75,995.00,922.00,980.0,969.30,965.65,2977470,2.875200e+14,19171.0,816123,2007,12,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3317,725.35,733.00,739.65,728.90,729.2,730.75,733.25,9390549,6.885658e+14,116457.0,838079,2021,4,26
3318,730.75,735.00,757.50,727.35,748.6,749.15,747.67,20573107,1.538191e+15,236896.0,1779639,2021,4,27
3319,749.15,755.00,760.00,741.10,743.4,746.25,751.02,11156977,8.379106e+14,130847.0,1342353,2021,4,28
3320,746.25,753.20,765.85,743.40,746.4,746.75,753.06,13851910,1.043139e+15,153293.0,1304895,2021,4,29
3321,746.75,739.00,759.45,724.50,726.4,730.05,743.35,12600934,9.366911e+14,132141.0,3514692,2021,4,30

In [50]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(xtrain, ytrain)

ValueError: Input X contains NaN.
LinearRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values